[project]
name = "hogtrace"
version = "0.1.0"
description = "DTrace-inspired instrumentation language for Python web applications"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "antlr4-tools>=0.2.2",
    "antlr4-python3-runtime>=4.13.2",
]
authors = [
    {name = "PostHog", email = "hey@posthog.com"}
]
keywords = ["tracing", "instrumentation", "observability", "dtrace", "posthog"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Debuggers",
    "Programming Language :: Python :: 3.12",
]

[project.optional-dependencies]
dev = [
    "ipython>=9.6.0",
]

[project.scripts]
hogtrace = "main:main"

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
